### ISSUE TITLE
end to end gym environment example

### ISSUE THREAD

**Issue by LukeWood** [google-deepmind/mctx#4]
Thanks for open sourcing!  

This is great and really cool to see the "curtain pulled back" a bit.  

Any chance we can have an example using a real environment?  Perhaps from openai-gym?  Maybe a community member can contribute this

or perhaps if this is too complex this can just be omitted.

**Comment by fidlej** [comment]
The end-to-end training scripts can be built by combining multiple libraries: mctx, optax, jaxline, haiku or some other frameworks.
Try to build something and ask questions, if an equation is unclear.

**Comment by ipsec** [comment]
A minimal example for cartpole gym game would be great

**Comment by kenjyoung** [comment]
This might be helpful:
https://github.com/kenjyoung/mctx_learning_demo
It includes a basic implementation of a learning algorithm on top of MCTX's tree search. It assumes the agent has access to exact environment dynamics. It does not learn a model but rather a policy and value function similar to AlphaZero. 

I did not use gym specifically since it's important that the env is written in jax here so it can be used directly in the tree search. The included environment is similar (though not identical) to Asterix from [MinAtar](https://github.com/kenjyoung/MinAtar). Other environments (including cartpole) could be implemented easily as long as they use the same interface. 

If anyone notices any issues with it please do let me know :)

**Comment by fidlej** [comment]
Some comments:
- Thanks @kenjyoung for the demo. The code looks nice.
- If people want to see benefits from the Monte Carlo tree search, use a deterministic environment that requires planning. For example, choose games which require a human to think for a few seconds before producing a good move. Carpole does not require MCTS.
- Pseudocode for MuZero is on arxiv: https://arxiv.org/src/1911.08265v2/anc/pseudocode.py
- The MuZero network architecture is in the appendix of "Policy improvement by planning with Gumbel":
https://openreview.net/pdf?id=bERaNdoegnO

**Comment by kenjyoung** [comment]
@fidlej You're welcome!

I also wanted to note that since my initial comment I have updated that repo with an additional Jax environment consisting of procedurally generated mazes. I think this is a much more illustrative use case for MCTS with learning than the original Asterix environment.
