### ISSUE TITLE
few questions about setting hyperparameters

### ISSUE THREAD

**Issue by Nightbringers** [google-deepmind/mctx#62]
In go game, the default value for "max_num_considered_actions" is 16. I want to know if this value should increase with the increase of num_simulations？Also maxvisit_init ?  What value is better for max_num_considered_actions when num_simulations is 400 and 800 and 1600?   There are a few other hyperparameters that I'm not sure how to set optimally.   I hope you can help me check how the settings are.  Do I need to adjust qtransform?
for go 19*19,  my settings is:
policy_output = mctx.gumbel_muzero_policy(
        ...
        num_simulations=400,
        max_num_considered_actions = 32,
        qtransform=partial(
            mctx.qtransform_completed_by_mix_value,
            value_scale=0.1,
            maxvisit_init=50,
            rescale_values=False,
        ),
        gumbel_scale=1.0,
    )

**Comment by fidlej** [comment]
Thanks for asking.
The rescale_values=False is good for Go. You can then use value_scale=1.0.
Otherwise, I would keep the defaults unchanged.

I do not have many results from 19x19 Go.
On 9x9 Go, the max_num_considered_actions was not very important, as you can see from Figure 3b.
https://openreview.net/pdf?id=bERaNdoegnO
