### ISSUE TITLE
Combining Gumbel MuZero and Stochastic MuZero

### ISSUE THREAD

**Issue by carlosgmartin** [google-deepmind/mctx#66]
This library contains implementations of

- [Gumbel MuZero](https://openreview.net/forum?id=bERaNdoegnO) (policy improvement)
- [Stochastic MuZero](https://openreview.net/forum?id=X6D9bAHhBQ1) (chance nodes)

Potentially, these could be combined. ([Example](https://ieeexplore.ieee.org/document/10056566).) I was wondering if any consideration has been given to the idea of adding an implementation of this combination.

**Comment by fidlej** [comment]
Hi. Thanks for asking.
Yes, it should be possible to combine the two algorithms. The Gumbel MuZero would be used for root nodes and Stochastic MuZero for interior nodes.

Currently, the Stochastic MuZero implementation is missing [tests with an expected search tree](https://github.com/google-deepmind/mctx/blob/272207f1e15f94b364eaf4e7d199365e3a3dcb64/mctx/_src/tests/tree_test.py#L155).
It would be nice to have such tests for any new implementation. E.g., recording a search tree from a 2048 game.

It would be also nice to move the Stochastic-MuZero-related policies to a new file: stochastic.py.
Currently, I'm not working with 2048 (or another stochastic game). Well-tested contributions are welcome here.

**Comment by carlosgmartin** [comment]
@fidlej [pgx](https://github.com/sotetsuk/pgx) and [jumanji](https://github.com/instadeepai/jumanji) have JAX implementations of 2048 that could perhaps be used for this.

**Comment by fidlej** [comment]
Let's close this issue.
The existing Stochastic MuZero implementation is not efficient inside mctx.
An alternative library can be created for Stochastic MuZero.

**Comment by puyuan1996** [comment]
Hello, thank you to the contributors for their outstanding work on this repository. Regarding the issue here, you might be interested in the project "[LightZero: A Unified Benchmark for Monte Carlo Tree Search in General Sequential Decision Scenarios](https://github.com/opendilab/LightZero)". This repository not only supports the AlphaZero algorithm but also extends support to MuZero and a series of related algorithms and environments (including **StochasticMuZero and 2048**), which might meet your requirements. Best wishes.
