### ISSUE TITLE
Sampled MuZero

### ISSUE THREAD

**Issue by carlosgmartin** [google-deepmind/mctx#87]
Would you consider adding support for [Sampled MuZero](https://arxiv.org/abs/2104.06303)?

**Comment by fidlej** [comment]
Maybe MCTS is not well suited for a large number of actions or for continuous actions.
You can use policy gradients or a simpler search there.

**Comment by puyuan1996** [comment]
Hello, thank you to the contributors for their outstanding work on this repository. Regarding the issue here, you might be interested in the project "[LightZero: A Unified Benchmark for Monte Carlo Tree Search in General Sequential Decision Scenarios](https://github.com/opendilab/LightZero)". This repository not only supports the AlphaZero algorithm but also extends support to MuZero and a series of related algorithms and environments (including **SampledMuZero** variants), which might meet your requirements. Best wishes.

**Comment by carlosgmartin** [comment]
@puyuan1996 Does LightZero plan to support JAX? I previously asked about that [here](https://github.com/opendilab/LightZero/issues/180) a while ago.

**Comment by puyuan1996** [comment]
Hello, given that the developers of this repository do not intend to support Sampled MuZero, we plan to optimize the [existing pytorch+cpp version](https://github.com/opendilab/LightZero/blob/main/lzero/policy/sampled_efficientzero.py) of the Sampled MuZero algorithm variant in [LightZero](https://github.com/opendilab/LightZero) in the near future. After the optimization is completed, considering that some users may not be familiar with cpp, we may provide a jax version to facilitate their use and research. At the same time, we are very welcoming and hope that community contributors can provide help in migration and discussion during this process, for which we will be extremely grateful. For related discussions and progress, you can follow this link (https://github.com/opendilab/LightZero/issues/210). Thank you.
